Repository apache/incubator-pegasus, pull requests merged in 2018-07, with the labels that each got.

#114 *: use buf2int/buf2bool in string_conv.h instead of which in pegasus_…
  src/base/pegasus_utils.cpp
  src/base/pegasus_utils.h
  src/redis_protocol/proxy_lib/redis_parser.cpp
  src/redis_protocol/proxy_ut/redis_proxy_test.cpp
  src/server/pegasus_write_service_impl.h
  src/shell/commands.h
Labels: enhancement

#115 scripts: add pegasus_replica_thread.sh
  scripts/pegasus_replica_thread.sh
Labels: scripts

#122 server: support check_and_set
  scripts/falcon_screen.json
  scripts/pegasus_replica_thread.sh
  src/base/pegasus_rpc_types.h
  src/base/pegasus_utils.h
  src/base/rrdb_types.cpp
  src/client_lib/pegasus_client_impl.cpp
  src/client_lib/pegasus_client_impl.h
  src/idl/recompile_thrift.sh
  src/idl/rrdb.thrift
  src/include/pegasus/client.h
  src/include/rrdb/rrdb.client.h
  src/include/rrdb/rrdb.code.definition.h
  src/include/rrdb/rrdb.server.h
  src/include/rrdb/rrdb.types.h
  src/include/rrdb/rrdb_types.h
  src/server/info_collector.cpp
  src/server/info_collector.h
  src/server/pegasus_server_impl.cpp
  src/server/pegasus_server_impl.h
  src/server/pegasus_server_write.cpp
  src/server/pegasus_write_service.cpp
  src/server/pegasus_write_service.h
  src/server/pegasus_write_service_impl.h
  src/shell/command_helper.h
  src/shell/commands.h
  src/shell/main.cpp
  src/test/function_test/run.sh
  src/test/function_test/test_check_and_set.cpp
Labels: new feature

#128 server: fix unpassed unit test & bug of CI
  src/server/test/pegasus_write_service_test.cpp
  src/server/test/run.sh
Labels: bug
