Repository apache/incubator-pegasus, pull requests merged in 2019-06, with the labels that each got.

#334 pegasus_server: fix set usage scenario problem when open db
  src/server/pegasus_server_impl.cpp
  src/server/pegasus_server_impl.h
Labels: type/bug-fix

#333 perf-counter: improve log printing when processing http response
  src/reporter/pegasus_counter_reporter.cpp
Labels: type/maintenance

#338 refactor: remove some useless configs
  .arcconfig
  src/base/test/config.ini
  src/geo/bench/config.ini
  src/geo/test/config.ini
  src/redis_protocol/proxy/config.ini
  src/redis_protocol/proxy_ut/config.ini
  src/sample/config.ini
  src/server/config-server.ini
  src/server/config.ini
  src/server/test/config.ini
  src/shell/config.ini
  src/test/bench_test/config.ini
  src/test/function_test/config.ini
  src/test/kill_test/config.ini
  src/test/upgrade_test/config.ini
Labels: component/configs, type/refactoring

#335 docker: add scripts for packing docker image & local docker cluster d…
  .gitignore
  docker/build_docker.sh
  docker/clear_onebox.sh
  docker/cluster_args.sh
  docker/dev/jepsen/Dockerfile
  docker/dev/jepsen/entrypoint.sh
  docker/dev/linux/Dockerfile
  docker/dev/linux/entrypoint.sh
  docker/docker-compose.yml
  docker/prepare.sh
  docker/start_onebox.sh
  scripts/pack_client.sh
  scripts/pack_server.sh
  scripts/pack_tools.sh
Labels: component/scripts
