Repository apache/incubator-pegasus, pull requests merged in 2020-01, with the labels that each got.

#399 feat(dup): implement pegasus_mutation_duplicator
  src/base/pegasus_key_schema.h
  src/base/pegasus_rpc_types.h
  src/base/rrdb_types.cpp
  src/client_lib/pegasus_client_impl.cpp
  src/client_lib/pegasus_client_impl.h
  src/idl/dsn.thrift
  src/idl/rrdb.thrift
  src/include/rrdb/rrdb.client.h
  src/include/rrdb/rrdb.code.definition.h
  src/include/rrdb/rrdb_types.h
  src/server/pegasus_mutation_duplicator.cpp
  src/server/pegasus_mutation_duplicator.h
  src/server/pegasus_write_service.h
  src/server/test/CMakeLists.txt
  src/server/test/config.ini
  src/server/test/pegasus_mutation_duplicator_test.cpp
Labels: component/duplication

#450 feat(rocksdb): Select the option of Direct-IO in Rocksdb
  src/server/pegasus_server_impl.cpp
Labels: type/configChange

#456 feat(dup): implement server handling of duplicate rpc (part 1)
  src/base/pegasus_value_schema.h
  src/base/rrdb_types.cpp
  src/idl/rrdb.thrift
  src/include/rrdb/rrdb_types.h
  src/server/pegasus_mutation_duplicator.cpp
  src/server/pegasus_server_write.cpp
  src/server/pegasus_server_write.h
  src/server/pegasus_write_service.cpp
  src/server/pegasus_write_service.h
  src/server/pegasus_write_service_impl.h
  src/server/test/pegasus_write_service_test.cpp
Labels: component/duplication

#462 refactor(config): remove duplicated config items for cluster name
  src/reporter/pegasus_counter_reporter.cpp
  src/server/available_detector.cpp
  src/server/config.ini
  src/server/config.min.ini
  src/server/info_collector.cpp
Labels: type/config-change
