Repository apache/incubator-pegasus, pull requests merged in 2020-04, with the labels that each got.

#508 fix(shell): disk_replica printer bug
  src/shell/commands/disk_rebalance.cpp
Labels: type/bug-fix

#505 feat(collector): add throughput statistic for table
  src/server/capacity_unit_calculator.cpp
  src/server/capacity_unit_calculator.h
  src/server/info_collector.cpp
  src/server/info_collector.h
  src/server/pegasus_server_impl.cpp
  src/server/pegasus_write_service.cpp
  src/server/table_stats.h
  src/server/test/capacity_unit_calculator_test.cpp
  src/shell/command_helper.h
Labels: type/perf-counter

#512 fix(collector): throughput statistics isn’t right
  src/shell/command_helper.h
Labels: type/bug-fix

#511 fix: node qps sum inconsistent with app qps sum
  src/shell/commands.h
  src/shell/commands/node_management.cpp
Labels: type/bug-fix

#514 fix(collector): no validate the app_name after parse_app_perf_counter_name
  src/shell/command_helper.h
Labels: type/bug-fix

#515 fix: fix the bug in restore_test
  src/server/config.min.ini
  src/test/function_test/test_restore.cpp
Labels: type/bug-fix

#520 feat(dup): support shell set fail_mode and collector duplication ops
  src/server/config.min.ini
  src/server/info_collector.cpp
  src/server/info_collector.h
  src/server/pegasus_mutation_duplicator.cpp
  src/server/pegasus_mutation_duplicator.h
  src/server/table_stats.h
  src/server/test/config.ini
  src/server/test/pegasus_mutation_duplicator_test.cpp
  src/shell/command_helper.h
  src/shell/commands.h
  src/shell/commands/duplication.cpp
  src/shell/main.cpp
Labels: component/duplication, type/perf-counter
